# Generated by Django 3.2.5 on 2021-09-12 07:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('image', models.TextField(blank=True, null=True)),
                ('login_count', models.IntegerField(default=0)),
                ('prior_experience', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='YearRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smallest_age', models.IntegerField(default=1)),
                ('highest_age', models.IntegerField(default=1)),
                ('range', models.CharField(default='8 - 9 years', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('age_range', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='online.yearrange')),
                ('features', models.ManyToManyField(to='online.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('headline', models.TextField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('icon', models.TextField(blank=True)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='online.level')),
            ],
        ),
    ]
